
import {
  gow1,
  gow2,
  sm1,
  sm2,
  manila1,
  manila2,
  taskmaster1,
  taskmaster2,
  taskmaster3,
  recipe1,
  recipe2,
  recipe3,
  tkinter1,
  tkinter2,
} from "../assets";

export const navigation = [
  {
    id: "0",
    title: "About",
    url: "#about",
  },
  {
    id: "1",
    title: "Projects",
    url: "#projects",
  },
  {
    id: "2",
    title: "Contact",
    url: "#contact",
  },
];

export const projectDetails = [
  {
    id: "0",
    title: "God of War Website",
    urlTitle: "My_First_Website",
    img1: gow1,
    img2: gow2,
    createdWhen: "Created on 1st yr of College",
    url: "https://gabrielasis.github.io/",
    categories: ["html", "css", "js"],
    flex: "col",
  },
  {
    id: "1",
    title: "Spider-Man 2 Website",
    urlTitle: "Responsive_Website",
    img1: sm1,
    img2: sm2,
    createdWhen: "Created on 2nd yr of College",
    url: "https://gabrielgonoasis.github.io/",
    categories: ["html", "css", "js", "responsive"],
    flex: "col",
  },
  {
    id: "2",
    title: "TaskMaster App",
    urlTitle: "Todo_List_Android_App",
    img1: taskmaster1,
    img2: taskmaster2,
    img3: taskmaster3,
    createdWhen: "Created on 2nd yr of College",
    url: "https://github.com/GabrielAsis/TaskMaster-App.git",
    categories: ["figma", "android", "js", "responsive"],
    flex: "row",

  },
  {
    id: "3",
    title: "Manila Brothers Website",
    urlTitle: "Group_Project_Website",
    img1: manila1,
    img2: manila2,
    createdWhen: "Created on 2nd yr of College",
    url: "https://github.com/Hamadn/Manilla-Brothers.git",
    categories: ["react", "tailwind"],
    flex: "col",
  },
  {
    id: "4",
    title: "Recipe App Prototype",
    urlTitle: "Figma_App_Prototype",
    img1: recipe1,
    img2: recipe2,
    img3: recipe3,
    createdWhen: "Created on 1st yr of College",
    url: "https://www.figma.com/design/hZJJzL6EkHKcd8JLUwbwTU/HiFi-Prototype?node-id=0-1&t=Zda8QgrImBMyb1zv-1",
    categories: ["figma"],
    flex: "row",
  },
  {
    id: "5",
    title: "Tkinter Movie App",
    urlTitle: "Tkinter_Python_App",
    img1: tkinter1,
    img2: tkinter2,
    createdWhen: "Created on 2nd yr of College",
    url: "https://github.com/GabrielAsis/Data-Driven-App.git",
    categories: ["python", "json", "api"],
    flex: "col",
  },
];