
import {
  gow1,
  gow2,
  sm1,
  sm2,
  taskmaster1,
  taskmaster,
  tkinter1,
  aifod,
  iubb,
  kuu,
  lexchina,
  zaan,
  themecrafted,
  trivio,
} from "../assets";

export const navigation = [
  {
    id: "0",
    title: "About",
    url: "#about",
  },
  {
    id: "1",
    title: "Projects",
    url: "#projects",
  },
  {
    id: "2",
    title: "Contact",
    url: "#contact",
  },
];

export const projectDetails = [
  {
    id: "0",
    title: "God of War Website",
    urlTitle: "My_First_Website",
    img1: gow1,
    createdWhen: "Created on 1st yr of College",
    url: "https://gabrielasis.github.io/",
    categories: ["Frontend", "Landing Page"],
    flex: "col",
  },
  {
    id: "1",
    title: "Spider-Man 2 Website",
    urlTitle: "Responsive_Website",
    img1: sm1,
    createdWhen: "Created on 2nd yr of College",
    url: "https://gabrielgonoasis.github.io/",
    categories: ["Frontend", "Landing Page"],
    flex: "col",
  },
  {
    id: "2",
    title: "TaskMaster App",
    urlTitle: "Todo_List_Android_App",
    img1: taskmaster,
    createdWhen: "Created on 2nd yr of College",
    url: "https://github.com/GabrielAsis/TaskMaster-App.git",
    categories: ["Smartphone App"],
    flex: "row",

  },
  {
    id: "3",
    title: "Tkinter Movie Pythong Project",
    urlTitle: "Tkinter_Python_App",
    img1: tkinter1,
    createdWhen: "Created on 2nd yr of College",
    url: "https://github.com/GabrielAsis/Data-Driven-App.git",
    categories: ["Python"],
    flex: "col",
  },
  {
    id: "4",
    title: "AI for Developing Countries Forum",
    img1: aifod,
    createdWhen: "Created on 2nd yr of College",
    url: "https://aifod.org/",
    categories: ["WordPress", "Organization"],
    flex: "col",
  },
  {
    id: "5",
    title: "KUU China",
    img1: kuu,
    createdWhen: "Created on 2nd yr of College",
    url: "https://www.kuu.net/index.php/en/",
    categories: ["WordPress", "Landing Page"],
    flex: "col",
  },
  {
    id: "6",
    title: "LexChina",
    img1: lexchina,
    createdWhen: "Created on 2nd yr of College",
    url: "https://lexchina.org/",
    categories: ["WordPress", "Organization"],
    flex: "col",
  },
  {
    id: "7",
    title: "Zaan",
    img1: zaan,
    url: "https://zaan.com/",
    categories: ["WordPress", "Tech Startup"],
    flex: "col",
  },
  {
    id: "8",
    title: "ThemeCrafted",
    img1: themecrafted,
    url: "https://themecrafted-frontend.onrender.com/",
    categories: ["Full-Stack", "E-commerce"],
    flex: "col",
  },
  {
    id: "9",
    title: "Trivio",
    img1: trivio,
    url: "https://trivio-site.vercel.app/",
    categories: ["Full-Stack"],
    flex: "col",
  },
];